version: "3.8"

services:
  postgres:
    container_name: nodejs-fastify-prisma-solid
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=fastify-prisma
